name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  - pip=23.3.1
  - scikit-learn=1.3.2
  - jupyterlab=4.1.3
  - ipywidgets=8.1.5
  - seaborn=0.11.1
  - ydata-profiling=4.10
  - pyarrow=2.0
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - ipykernel==6.29.5
